### ISSUE TITLE
Roster class seems to be broken

### ISSUE THREAD

**Issue by dereulenspiegel** [rtreffer/asmack#2]
Since the integration of BOSH the complete roster handling seems to be broken. The roster listeners aren't notified of any changes, the roster class does not contain any entries after loading and the roster is loaded all over again the whole time. I should mention that I don't let the roster load at login but call Roster.reload() after I added my custom roster listener. With previous versions I didn't had this problem and everything worked fine. I hope this could be fixed easily.

Greetings

**Comment by rtreffer** [comment]
Yes, I can confirm this, actually the roster parsing was move to PacketParserUtil, and a correct packet seems to be created (I've just added a simple "dump" of the added items, and there are all the contects visible).

I'm currently stepping through the code to see where it get losts., as the Roster should pick up the Packet....

Regards,
  RT

**Comment by rtreffer** [comment]
I think I know what's going on, clients getRoster while the Roster is still loading. I've also got extremly slow Roster insertion. So your app will most likely get an empty Roster on getRoster.

I'll see why the method isn't blocking.

Regards,
  RT

**Comment by rtreffer** [comment]
The issue was that getRoster called getRoster via a wired loop.

http://github.com/rtreffer/asmack/commit/9dd53d18b06e85a877ce109a4da31062e3040e1a shoudl fix it. New uploads are a matter of minutes.

Regards,
  René
